import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>ViewTransitionApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.section}>
        <div className={styles.image}>
          <Image
            src={`/author.png`}
            width={600}
            height={600}
            alt="Picture of the author"
            style={{
              height: "auto",
              borderRadius: "999px",
              viewTransitionName: "author-image",
            }}
          />
        </div>
        <p className={styles.copy}>welcome to my page!</p>
      </section>
    </>
  );
}
